### ISSUE TITLE
Question: Upload API for neurovault?

### ISSUE THREAD

**Issue by dfsp-spirit** [muschellij2/neurovault#2]
Dear John,

thanks for this package. I am interested in **uploading** data to Neurovault via the API, but could not find any [API documentation](https://neurovault.org/api-docs) on that. I had a look at an [outdated Python tool](https://github.com/NeuroVault/pyneurovault), adapted the queries to R and was able to create a collection remotely via R, but that's it.

The Neurovault repo seems unmaintained atm and my issue/question there was never answered. I was just wondering whether you know anything about an upload API?

Best,

Tim

**Comment by muschellij2** [comment]
It looks that going to the root API, it's not in their functionality: https://neurovault.org/api/.  I'd reach to @poldrack and @poldracklab as they are the creators.

**Comment by muschellij2** [comment]
I think you can login and create a new collection, but it has to be done through their GUI.
